project:
  type: website
  output-dir: docs

# Global execution options
execute:
  freeze: auto

website:
  title: ""
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      # - text: "Independent Projects"
      #   href: index.qmd
      - text: "Analytical Projects"
        menu:
          - text: "Patient Satisfaction"
            href: ptsatisfaction.qmd
          - text: "FFS Medicare Benefeciaries"
            href: ffsgvmedicare.qmd
      - text: "Concepts"
        menu: 
          - text: "Fantasy Football"
            href: fantasyfootball.qmd
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: "https://github.com/S1atty"
      - icon: linkedin
        href: "https://www.linkedin.com/in/adetomi-akisanya-4b263724a/"
      - icon: instagram
        href: "https://www.instagram.com/tomi_a999/"
        
format:
  html: 
    grid:
      sidebar-width: 200px
      body-width: 1100px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    mainfont: Garamond;
    toc: true
    toc-depth: 2
    css: styles.css

